name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liXt0lQqTaOdLM6c"
GITHUB_OWNER = "frleev"
GITHUB_REPO = "Nav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://frlee.pages.dev/"
NEXT_PUBLIC_API_URL="https://frlee.pages.dev/"

